### ISSUE TITLE
Cannot find module 'del'

### ISSUE THREAD

**Issue by TheSharpieOne** [sindresorhus/del-cli#1]
del is not listed as a dependency in the package.json.

**Comment by sindresorhus** [comment]
Thanks for letting me know. Fixed now.

**Comment by sindresorhus** [comment]
Explanation:

> I fell victim to npm@3 flattening. Test didn't fail when I forgot to include `del` as a direct dependency since npm@3 maximally flattens the dependency three and a deep dev dependency on `del` were moved to the top-level: del-cli → xo → eslint → file-entry-cache → flat-cache → del, which meant tests passed, but it of course failed when installed :(

**Comment by iamstarkov** [comment]
maybe this should be reported as a bug to npm? /cc @othiym23

**Comment by nupur2710** [comment]
Was this fixed in any new versions of npm?
