### ISSUE TITLE
Request: verbose option

### ISSUE THREAD

**Issue by evanwarner** [sindresorhus/del-cli#10]
It would be great to have a `--verbose` option that outputs the files being deleted in realtime. I know about `--dry-run` for testing, but I'd like this for actual execution too.

**Comment by sindresorhus** [comment]
For what purpose?

**Comment by evanwarner** [comment]
I just got the close notification but never saw your question from July, sorry! To answer you, I had a project where initial testing was fine but later on as I was working, a typo in my config caused the wrong folder to get caught up in the deletion task. I only noticed because the deletion task was taking way longer than it should have and I aborted. Running it again with `--dry-run` showed me a list of files I didn't intend to delete. Manually reconciling the error took a while, and if I'd at least had an output of what got deleted, it would have been a bit easier.
