### ISSUE TITLE
doesn't work with windows absolute paths

### ISSUE THREAD

**Issue by alexander-akait** [sindresorhus/del-cli#14]
Reproducible example:
```shell
del D:\a\plugin\name\__tests__\dir\nested
```

Output with `1` exit code:
```
The filename, directory name, or volume label syntax is incorrect.
```

I think problem in `globby` (maybe in `fast-glob`)

**Comment by sindresorhus** [comment]
You have to use `del-cli` on Windows. `del` is already a built-in command there.
