### ISSUE TITLE
Potential issues with process.exit(1)

### ISSUE THREAD

**Issue by kitsune7** [sindresorhus/del-cli#18]
`console.error` is synchronous as far as I'm aware, so this may not be an issue, but I thought I would bring it up regardless. Feel free to close this issue if you think it's more work than it's worth.

In `cli.js` there's a code segment that uses `process.exit(1)` right after logging to stderr.

```javascript
if (cli.input.length === 0) {
	console.error('Specify at least one path');
	process.exit(1);
}
```

While I don't think this would be an issue in most cases, calling `process.exit(1)` [isn't recommended practice](https://nodejs.org/api/process.html#process_process_exit_code). It's better to use `process.exitCode = 1` and then just prevent the function after it from running with else.

See [this StackOverflow thread](https://stackoverflow.com/a/37592669/3991628) for more details.

**Comment by sindresorhus** [comment]
I would usually agree, but in this case, it doesn't really matter. Also, for context, this code was written before `process.exitCode = ` was the best-practice. However, I guess, it doesn't hurt to change it.
