### ISSUE TITLE
Add `--verbose` flag

### ISSUE THREAD

**Issue by fisker** [sindresorhus/del-cli#24]
When run `del-cli` on huge directory, I'd like to see the progress.

**Comment by sindresorhus** [comment]
What would it look like? Progress bar, showing each file as it's being deleted, something else?

**Comment by fisker** [comment]
> showing each file as it's being deleted

This. 

> Progress bar

Not care that much.

> something else?

Nope.

**Comment by sindresorhus** [comment]
Yeah, sounds good. We'll need to add a `progress` event to https://github.com/sindresorhus/del/issues/133

Similar to https://github.com/sindresorhus/cpy#progress-reporting

The flag should be `--verbose`.

**Comment by fisker** [comment]
Don't you think return a generator instead of sorted array in `del` can have better performance? Unless we want know the length of matched files.

**Comment by sindresorhus** [comment]
Why would a generator have better performance? It has to go through all the files anyway. Unless I'm misunderstanding what you mean?

**Comment by fisker** [comment]
You're right, I thought it run delete after sort, never mind.
