### ISSUE TITLE
difference with rimraf ?

### ISSUE THREAD

**Issue by mesqueeb** [sindresorhus/del-cli#26]
I'm interested to know the difference between this and the `rimraf` node package, or `rm -rf` on macOS.

Thanks in advance! : )

**Comment by sindresorhus** [comment]
Benefits over `rimraf` CLI: Supports globbing (even on Windows), safer by default as it doesn't allow deleting parent directories, has a dry-run mode.

Benefits over `rm -rf`: Cross-platform, safer by default as it doesn't allow deleting parent directories, has a dry-run mode.

**Comment by mesqueeb** [comment]
@sindresorhus I wonder if "del-cli" is really cross-platform if you need to write `del-cli` on windows, what should we do with our package.json scripts? If our team has both windows & mac users. Is there a keyword that works on both mac and windows? Because otherwise it's not really cross-platform.

**Comment by sindresorhus** [comment]
If your project is cross-platform, you use `del-cli`. It works on both.

**Comment by sindresorhus** [comment]
If your project is cross-platform, you use `del-cli`. It works on both.
