### ISSUE TITLE
del with glob argument in package.json script fails on windows only but del-cli works

### ISSUE THREAD

**Issue by jharris4** [sindresorhus/del-cli#32]
Hi, I recently tried out replacing `rimraf` with `del-cli` and it went super smoothly except we hit some windows specific issues that our automated tests caught.

Specifically, if you have a `package.json` file with the following:

```
{
  "devDependencies": {
    "del-cli": "^5.0.0"
  },
  "scripts": {
    "test": "del someExistingDir/*"
  }
}
```

This works on ubuntu, macos but errors on windows.

I created a minimal reproduction here:

https://github.com/jharris4/del-cli-test

And you can see the failing test here: 

https://github.com/jharris4/del-cli-test/actions/runs/4478499761

The error that is reported is only on windows and is quite strange:

`Invalid switch - "*"`

It seems that anything after the `/` in the glob path gets reported in this error.

By pure luck, I did find a workaround for this issue which was to use the `del-cli` node bin instead of the `del` node bin like the following:

```
{
  "devDependencies": {
    "del-cli": "^5.0.0"
  },
  "scripts": {
    "test": "del-cli someExistingDir/*"
  }
}
```

With this workaround everything runs smoothly on ubuntu/macos/windows...

**Comment by sindresorhus** [comment]
From the readme:

> ⚠️ Windows users: Since $ del is already a builtin command on Windows, you need to use $ del-cli there.

**Comment by jharris4** [comment]
Interesting, it seems to be calling the native windows del command instead of the node bin

**Comment by jharris4** [comment]
> From the readme:
> 
> > ⚠️ Windows users: Since $ del is already a builtin command on Windows, you need to use $ del-cli there.

Wow, I don't know how my brain totally missed that from the README. Glad this is documented already, thanks!
