### ISSUE TITLE
Cannot handle * matches Windows

### ISSUE THREAD

**Issue by wChenonly** [sindresorhus/del-cli#33]
![img_v2_1bff8eb1-b8a2-463a-a2d4-2ba17d7f0b5g](https://github.com/sindresorhus/del-cli/assets/37658262/fe996631-2ac0-4279-bea1-8086eef3c332)

**Comment by sindresorhus** [comment]
You need to wrap the glob pattern in quotes.

**Comment by wChenonly** [comment]
this ?   "compiler:clean": "del packages/'*'/src/icons"   Still wrong
