### ISSUE TITLE
Option to delete dotfiles

### ISSUE THREAD

**Issue by callumlocke** [sindresorhus/del-cli#6]
I expected `del ./**` to clear my current working directory, but it leaves dotfiles intact.

Can this be changed, or a flag be added to allow deleting dotfiles?

**Comment by schnittstabil** [comment]
I do not know why, but:

``` sh
del ./* --dot # works
del --dot ./* # does not
```

@callumlocke NB: `del ./**` also tries to remove the working directory. If you want that, you have to run `del --force ./** --dot`.

**Comment by callumlocke** [comment]
hmm, just tried `--dot` but it has no effect for me.

I can't see `dot` anywhere in the code: https://github.com/sindresorhus/del-cli/blob/master/cli.js

are you sure there's a `--dot` flag?

**Comment by schnittstabil** [comment]
The option is passed through `del`: [`cli.flags`](https://github.com/sindresorhus/del-cli/blob/master/cli.js#L37) (and [node-glob](https://github.com/isaacs/node-glob#options))

~~This should also work:~~ These work for me:

``` sh
$ find
# .
# ./.hidden

$ del ./* --dot
$ del --dot=true ./* # works too

$ find
# .
```

On Windows you may have to escape the pattern:

``` sh
del --dot=true "./*"
```

**Comment by SamVerschueren** [comment]
Closing this as the solution provided by @schnittstabil works. If you still experience issues, don't hesitate to respond.
